[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sec-agg"
version = "1.0.0"
description = ""
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.19.0",
    "flwr-datasets[vision]>=0.5.0",
    "torch==2.5.1",
    "torchvision==0.20.1",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "sec-agg"

[tool.flwr.app.components]
serverapp = "sec_agg.server_app:app"
clientapp = "sec_agg.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 3
fraction-fit = 0.5
local-epochs = 1
strategy = "HEFedAvg"  # or "HEKrum"
num-malicious = 2       # only used if strategy is HEKrum

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 10
