_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 30
                - 41
                - 49
                - 51
            "2":
                - 1
                - 30
                - 41
                - 49
                - 51
            "3":
                - 2
                - 13
                - 55
            "4": 3.10.18
            "5": 0.20.1
            "10":
                - 20
            "12": 0.20.1
            "13": darwin-x86_64
alpha:
    value: 0.1
local_epochs:
    value: 1
num_malicious:
    value: 4
num_partitions:
    value: 10
num_rounds:
    value: 10
run_name:
    value: he_krum_break_fail_f4_n10
strategy:
    value: HEKrum
